--- #YAML:1.0
name:               Parse-Stallion
version:            1.05
abstract:           EBNF based regexp backtracking parser and tree evaluator.
author:
    - Arthur Goldstein <arthur@acm.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:         0
    Test::More:   0
    Time::Local:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
